# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginyRegister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginyRegister(self):
    self.driver.get("https://pascualbravo.ingejei.com/wp-login.php?action=register")
    self.driver.find_element(By.ID, "user_login").send_keys("persona2")
    self.driver.find_element(By.ID, "user_email").send_keys("persona2@gmail.com")
    self.driver.find_element(By.ID, "wp-submit").click()
  
