# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregaryEliminarProductosCarrito():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregaryEliminarProductosCarrito(self):
    self.driver.get("https://pascualbravo.ingejei.com/wp-login.php")
    self.driver.find_element(By.ID, "user_login").send_keys("JEISIM18@GMAIL.COM")
    self.driver.find_element(By.ID, "user_pass	").send_keys("JEISIM18@GMAIL.COM")
    self.driver.get("https://pascualbravo.ingejei.com/?post_type=product")
    self.driver.find_element(By.CSS_SELECTOR, "button.add_to_cart_button[data-product_id=\"24\"]").click()
    self.driver.get("https://pascualbravo.ingejei.com/?page_id=7")
    self.driver.find_element(By.CSS_SELECTOR, "button.wc-block-cart-item__remove-link[aria-label*=\"Hamburguesa Rica\"]").click()
  
